
import Main.MasterThread;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import restaurante.entidades.ItemDoMenu;
import restaurante.entidades.Pedido;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David .V
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        filaDeEsperaTabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDoMenu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaListaDePreparo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPedidosConcluidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filaDeEsperaTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        masterThread = new MasterThread();
        filaDeEsperaTabela.setModel(masterThread.getlP().getModeloTabela());
        filaDeEsperaTabela.getColumnModel().getColumn(0).setHeaderValue("Prato");
        filaDeEsperaTabela.getColumnModel().getColumn(1).setHeaderValue("Tempo");
        tabelaDoMenu.setModel(masterThread.getlI().getModeloTabela());
        tabelaDoMenu.getColumnModel().getColumn(0).setHeaderValue("Prato");
        tabelaDoMenu.getColumnModel().getColumn(1).setHeaderValue("Tempo Medio de preparo");
        tabelaDoMenu.getColumnModel().getColumn(2).setHeaderValue("Valor");
        THMasterThread = new Thread(masterThread);
        THMasterThread.start();
        tabelaDoMenu.setModel(masterThread.getlI().getModeloTabela());
        tabelaDoMenu.getColumnModel().getColumn(0).setHeaderValue("Teste");
        jScrollPane1.setViewportView(filaDeEsperaTabela);

        tabelaDoMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Title 2", "Title 3", "Título 4"
            }
        ));
        tabelaDoMenu.setModel(masterThread.getlI().getModeloTabela());
        tabelaDoMenu.getColumnModel().getColumn(0).setHeaderValue("Id");
        tabelaDoMenu.getColumnModel().getColumn(1).setHeaderValue("Prato");
        tabelaDoMenu.getColumnModel().getColumn(2).setHeaderValue("Tempo de preparo");
        tabelaDoMenu.getColumnModel().getColumn(3).setHeaderValue("Preco");
        tabelaDoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDoMenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDoMenu);
        if (tabelaDoMenu.getColumnModel().getColumnCount() > 0) {
            tabelaDoMenu.getColumnModel().getColumn(0).setMinWidth(20);
            tabelaDoMenu.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabelaDoMenu.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        tabelaListaDePreparo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaListaDePreparo.setModel(masterThread.getListaDePreparo().getModeloTabela());
        tabelaListaDePreparo.getColumnModel().getColumn(0).setHeaderValue("Cozinheiro");
        tabelaListaDePreparo.getColumnModel().getColumn(1).setHeaderValue("Pedido");
        tabelaListaDePreparo.getColumnModel().getColumn(2).setHeaderValue("Tempo");
        jScrollPane3.setViewportView(tabelaListaDePreparo);

        jButton1.setText("Realizar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaPedidosConcluidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pedido", "Tempo total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPedidosConcluidos.setModel(masterThread.getTabelaDePedidosConcluidos().getModeloTabela());
        tabelaPedidosConcluidos.getColumnModel().getColumn(0).setHeaderValue("Pedido");
        tabelaPedidosConcluidos.getColumnModel().getColumn(1).setHeaderValue("Tempo total");
        jScrollPane4.setViewportView(tabelaPedidosConcluidos);
        if (tabelaPedidosConcluidos.getColumnModel().getColumnCount() > 0) {
            tabelaPedidosConcluidos.getColumnModel().getColumn(0).setResizable(false);
            tabelaPedidosConcluidos.getColumnModel().getColumn(1).setResizable(false);
            tabelaPedidosConcluidos.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        jLabel1.setText("Fila de pedidos em espera:");

        jLabel2.setText("Lista de cozinheiros:");

        jLabel3.setText("Menu:");

        jLabel4.setText("Lista de pedidos entregues:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tabelaDoMenu.isColumnSelected(1) || tabelaDoMenu.isColumnSelected(0) || tabelaDoMenu.isColumnSelected(2) || tabelaDoMenu.isColumnSelected(3)){
            Double aux = Double.parseDouble(tabelaDoMenu.getModel().getValueAt(tabelaDoMenu.getSelectedRow(), 4).toString());
            ItemDoMenu item = new ItemDoMenu(Integer.parseInt(tabelaDoMenu.getModel().getValueAt(tabelaDoMenu.getSelectedRow(), 0).toString()), tabelaDoMenu.getModel().getValueAt(tabelaDoMenu.getSelectedRow(), 1).toString(), Double.parseDouble(tabelaDoMenu.getModel().getValueAt(tabelaDoMenu.getSelectedRow(), 0).toString()),aux.longValue());
            Pedido pedido = new Pedido(item);
            masterThread.getlP().addPedido(pedido);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item da lista para realizar o pedido");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaDoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDoMenuMouseClicked
        
        
    }//GEN-LAST:event_tabelaDoMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable filaDeEsperaTabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable tabelaDoMenu;
    private javax.swing.JTable tabelaListaDePreparo;
    private javax.swing.JTable tabelaPedidosConcluidos;
    // End of variables declaration//GEN-END:variables
    public MasterThread masterThread;
    public Thread THMasterThread;
}
